### ISSUE TITLE
Sample image

### ISSUE THREAD

**Issue by alystair** [binarymax/bashfill#2]
If you consider putting together a gallery or need a sample design...

https://max.io/bash.html?zip=eDE1eTF4MjRlMXgzeTF4MzB5MXg1ZTF4NDBlMXg0eTJ4NXc1eDd5MXg3eTF4NncyZTF4M3kyeDRtMXc3eDE5bTF3M2UxdzJ4MXkyeDE1eTF4MTllMXc0eTJ4MnkxeDI2eTF4NGUxeDR5NHgxM3c1eDE0ZTF4MTltMXc3eDEzZTF4NDBlMXg0MGUxeDdiMWMydzF4N2IxYzJ3MXgxOGUxYjF4MWIxeDFiMXgxYjFjMm0xeDNiMXgxYjF4MWIxYzJtMXgyYjF4MWIxeDFiMXgxYjF4MWIxeDFiMXgxYjF4MWIxeDFiMWUxZzFjOW0zZzFjM2cxYzNtNGcxYzRtMWIxbTFiMWcxYzNiMW0xZTFtM2M0YjFtMWIxYzhtMmcxYzViMW0xYjFnMWM0YjFtMWIxbTFnMWMxZTFjMmIxbTFiMW0xYjFtMWcxYzViMW0xYjFnMWMzbTFiMW0xYjFnMWMzYjFtMWIxbTFiMWcxYzNtMWIxZTFtMmcxYzdiMW0xYjFtMWM0bTFjMWcxYzVtMWIxZzFjMTFlMWMzYjFtMWIxbTFiMW0xYjFnMWMzYjFtMWIxbTFjMTJiMm0xYjFtMWcxYzNtMWUxYzExbTFiMWM1YjF3NWMyYjFtMWIxYzN3M2IxbTFiMW0xYzFlMWMzdzJiMWM5YjJ3Mm01YjFjM3c0bTJ3MWIxYzRlMWMydzFtMncxYjl3Mm0yeTR3MW0xYjFjMXcxbTNjMXcxYzFtMXcxYjRlMXcybTF5M3cxMG0xeTh3Mm0xYzF5MWMxeTFjMXkydzVlMXk0MA==

Creative Commons blahblahblah, use as you will :)

**Comment by binarymax** [comment]
Nice one.  Thanks!

**Comment by binarymax** [comment]
Added sample to README
